"use client";
import { useEffect, useState } from "react";
import { Copy, Trash2, Search, LayoutTemplate } from "lucide-react";
import { Page } from "@/components/ui/page";
import type { EmailDocument } from "@/lib/email";

interface Template { id:string; name:string; description?:string; category?:string; document:EmailDocument; version:number; createdAt:string; }
export default function TemplatesPage(){
  const [items,setItems]=useState<Template[]>([]); const [q,setQ]=useState("");
  useEffect(()=>{fetch("/api/templates").then(r=>r.json()).then(setItems)},[]);
  const useTemplate=async(t:Template)=>{const r=await fetch("/api/emails",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:t.name,subject:t.document.metadata.subject,previewText:t.document.metadata.previewText,document:structuredClone(t.document)})});if(r.ok){const e=await r.json();location.href=`/emails/${e.id}/builder`}};
  const remove=async(id:string)=>{if(!confirm("Delete this template?"))return;await fetch(`/api/templates/${id}`,{method:"DELETE"});setItems(x=>x.filter(i=>i.id!==id))};
  const filtered=items.filter(t=>`${t.name} ${t.description??""} ${t.category??""}`.toLowerCase().includes(q.toLowerCase()));
  return <Page title="Templates" description="Reusable full-email designs you can start from."><div className="mb-6 flex items-center gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-zinc-400" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search templates…" className="w-full rounded-lg border bg-white py-2 pl-9 pr-3 text-sm"/></div></div>{filtered.length===0?<div className="rounded-xl border border-dashed bg-white p-12 text-center"><LayoutTemplate className="mx-auto mb-3 text-zinc-300"/><div className="font-medium">No templates yet</div><p className="mt-1 text-sm text-zinc-500">Save an email as a template from the builder and it will appear here.</p></div>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(t=><div key={t.id} className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="h-44 overflow-hidden bg-zinc-100"><TemplatePreview document={t.document}/></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{t.name}</h2><p className="mt-1 text-xs text-zinc-500">{t.description||"Reusable email design"}</p></div><button onClick={()=>remove(t.id)} className="rounded p-1.5 text-zinc-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></div><div className="mt-4 flex gap-2"><button onClick={()=>useTemplate(t)} className="flex-1 rounded-lg bg-zinc-900 px-3 py-2 text-xs font-semibold text-white">Use template</button><span className="rounded-lg bg-zinc-100 px-3 py-2 text-xs text-zinc-500">v{t.version}</span></div></div></div>)}</div>}</Page>
}
function TemplatePreview({document}:{document:EmailDocument}){return <div className="mx-auto h-full max-w-[300px] overflow-hidden bg-white p-3 text-[7px]"><div className="space-y-2">{document.children.map(n=><div key={n.id} className="rounded bg-zinc-50 p-2">{n.type==="heading"?<div className="text-base font-bold">{String(n.props?.content??"Heading")}</div>:n.type==="text"?<div className="text-zinc-500">{String(n.props?.content??"Text")}</div>:n.type==="image"?<div className="flex h-12 items-center justify-center bg-zinc-200">Image</div>:n.type==="button"?<div className="inline-block rounded bg-zinc-900 px-2 py-1 text-white">{String(n.props?.text??"Button")}</div>:<div className="text-zinc-400">{n.type}</div>}</div>)}</div></div>}
