import { pgTable, uuid, text, timestamp, integer, boolean, jsonb, index, uniqueIndex, primaryKey } from "drizzle-orm/pg-core";
import type { EmailComponent, EmailDocument } from "@/lib/email/types";
import { organization, user } from "./auth-schema";

export { organization, user } from "./auth-schema";

const timestamps = () => ({ createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });

export const emails = pgTable("emails", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), name: text("name").notNull(), description: text("description"), status: text("status").notNull().default("draft"), currentDocument: jsonb("current_document").$type<EmailDocument>().notNull(), createdBy: uuid("created_by").references(() => user.id), ...timestamps() }, t => ({ orgIdx: index("emails_org_idx").on(t.organizationId) }));
export const emailVersions = pgTable("email_versions", { id: uuid("id").defaultRandom().primaryKey(), emailId: uuid("email_id").references(() => emails.id).notNull(), versionNumber: integer("version_number").notNull(), document: jsonb("document").$type<EmailDocument>().notNull(), createdBy: uuid("created_by").references(() => user.id), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ versionIdx: uniqueIndex("email_versions_unique_idx").on(t.emailId, t.versionNumber) }));

export const contentCategories = pgTable("content_categories", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), name: text("name").notNull(), slug: text("slug").notNull(), ...timestamps() }, t => ({ orgSlugIdx: uniqueIndex("content_categories_org_slug_idx").on(t.organizationId, t.slug) }));
export const templates = pgTable("templates", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), name: text("name").notNull(), description: text("description"), category: text("category"), categoryId: uuid("category_id").references(() => contentCategories.id), visibility: text("visibility").notNull().default("private"), currentDocument: jsonb("current_document").$type<EmailDocument>().notNull(), createdBy: uuid("created_by").references(() => user.id), ...timestamps() });
export const templateVersions = pgTable("template_versions", { id: uuid("id").defaultRandom().primaryKey(), templateId: uuid("template_id").references(() => templates.id).notNull(), versionNumber: integer("version_number").notNull(), document: jsonb("document").$type<EmailDocument>().notNull(), createdBy: uuid("created_by").references(() => user.id), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ versionIdx: uniqueIndex("template_versions_unique_idx").on(t.templateId, t.versionNumber) }));
export const blocks = pgTable("blocks", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), name: text("name").notNull(), description: text("description"), category: text("category"), categoryId: uuid("category_id").references(() => contentCategories.id), visibility: text("visibility").notNull().default("private"), currentDocument: jsonb("current_document").$type<EmailComponent>().notNull(), inputs: jsonb("inputs"), createdBy: uuid("created_by").references(() => user.id), ...timestamps() });
export const blockVersions = pgTable("block_versions", { id: uuid("id").defaultRandom().primaryKey(), blockId: uuid("block_id").references(() => blocks.id).notNull(), versionNumber: integer("version_number").notNull(), document: jsonb("document").$type<EmailComponent>().notNull(), createdBy: uuid("created_by").references(() => user.id), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ versionIdx: uniqueIndex("block_versions_unique_idx").on(t.blockId, t.versionNumber) }));

export const assetFolders = pgTable("asset_folders", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), parentId: uuid("parent_id"), name: text("name").notNull(), ...timestamps() });
export const assets = pgTable("assets", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), folderId: uuid("folder_id").references(() => assetFolders.id), filename: text("filename").notNull(), originalFilename: text("original_filename").notNull(), mimeType: text("mime_type").notNull(), fileSize: integer("file_size").notNull(), width: integer("width"), height: integer("height"), storageProvider: text("storage_provider").notNull(), storageKey: text("storage_key").notNull(), publicUrl: text("public_url"), altText: text("alt_text"), metadata: jsonb("metadata"), createdBy: uuid("created_by").references(() => user.id), ...timestamps() }, t => ({ orgIdx: index("assets_org_idx").on(t.organizationId), keyIdx: uniqueIndex("assets_storage_key_idx").on(t.storageProvider, t.storageKey) }));
export const tags = pgTable("tags", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), name: text("name").notNull(), slug: text("slug").notNull() }, t => ({ orgSlugIdx: uniqueIndex("tags_org_slug_idx").on(t.organizationId, t.slug) }));
export const assetTags = pgTable("asset_tags", { assetId: uuid("asset_id").references(() => assets.id).notNull(), tagId: uuid("tag_id").references(() => tags.id).notNull() }, t => ({ pk: primaryKey({ columns: [t.assetId, t.tagId] }) }));

export const links = pgTable("links", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), name: text("name").notNull(), description: text("description"), destinationUrl: text("destination_url").notNull(), trackingEnabled: boolean("tracking_enabled").notNull().default(true), utmSource: text("utm_source"), utmMedium: text("utm_medium"), utmCampaign: text("utm_campaign"), utmTerm: text("utm_term"), utmContent: text("utm_content"), ...timestamps() });

export const contacts = pgTable("contacts", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), email: text("email").notNull(), firstName: text("first_name"), lastName: text("last_name"), status: text("status").notNull().default("subscribed"), ...timestamps() }, t => ({ emailOrgIdx: uniqueIndex("contacts_org_email_idx").on(t.organizationId, t.email) }));
export const contactLists = pgTable("contact_lists", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), name: text("name").notNull(), description: text("description"), ...timestamps() });
export const contactListMembers = pgTable("contact_list_members", { contactId: uuid("contact_id").references(() => contacts.id).notNull(), listId: uuid("list_id").references(() => contactLists.id).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ pk: primaryKey({ columns: [t.contactId, t.listId] }) }));
export const contactCustomFields = pgTable("contact_custom_fields", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), name: text("name").notNull(), slug: text("slug").notNull(), fieldType: text("field_type").notNull().default("text"), ...timestamps() }, t => ({ orgSlugIdx: uniqueIndex("contact_fields_org_slug_idx").on(t.organizationId, t.slug) }));
export const contactCustomValues = pgTable("contact_custom_values", { contactId: uuid("contact_id").references(() => contacts.id).notNull(), fieldId: uuid("field_id").references(() => contactCustomFields.id).notNull(), value: text("value") }, t => ({ pk: primaryKey({ columns: [t.contactId, t.fieldId] }) }));

export const emailDomains = pgTable("email_domains", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), domain: text("domain").notNull(), status: text("status").notNull().default("pending"), provider: text("provider"), verificationRecords: jsonb("verification_records"), ...timestamps() }, t => ({ orgDomainIdx: uniqueIndex("email_domains_org_domain_idx").on(t.organizationId, t.domain) }));
export const campaigns = pgTable("campaigns", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organization.id).notNull(), emailId: uuid("email_id").references(() => emails.id).notNull(), emailVersionId: uuid("email_version_id").references(() => emailVersions.id), name: text("name").notNull(), status: text("status").notNull().default("draft"), fromName: text("from_name"), fromEmail: text("from_email"), replyTo: text("reply_to"), subject: text("subject"), previewText: text("preview_text"), deliveryProvider: text("delivery_provider"), scheduledAt: timestamp("scheduled_at", { withTimezone: true }), ...timestamps() });
export const campaignRecipients = pgTable("campaign_recipients", { id: uuid("id").defaultRandom().primaryKey(), campaignId: uuid("campaign_id").references(() => campaigns.id).notNull(), contactId: uuid("contact_id").references(() => contacts.id).notNull(), email: text("email").notNull(), firstName: text("first_name"), lastName: text("last_name"), status: text("status").notNull().default("pending"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ campaignContactIdx: uniqueIndex("campaign_recipient_contact_idx").on(t.campaignId, t.contactId) }));
export const campaignRenderings = pgTable("campaign_renderings", { id: uuid("id").defaultRandom().primaryKey(), campaignId: uuid("campaign_id").references(() => campaigns.id).notNull(), html: text("html").notNull(), subject: text("subject"), previewText: text("preview_text"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const campaignEvents = pgTable("campaign_events", { id: uuid("id").defaultRandom().primaryKey(), campaignId: uuid("campaign_id").references(() => campaigns.id).notNull(), campaignRecipientId: uuid("campaign_recipient_id").references(() => campaignRecipients.id).notNull(), eventType: text("event_type").notNull(), linkId: uuid("link_id").references(() => links.id), occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(), metadata: jsonb("metadata") }, t => ({ campaignIdx: index("campaign_events_campaign_idx").on(t.campaignId), recipientIdx: index("campaign_events_recipient_idx").on(t.campaignRecipientId) }));
