"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import type { AssetRecord } from "@/lib/assets/types";

function formatBytes(n: number) { if (n < 1024) return `${n} B`; if (n < 1024 * 1024) return `${(n/1024).toFixed(0)} KB`; return `${(n/1024/1024).toFixed(1)} MB`; }

export default function AssetsPage() {
  const [assets, setAssets] = useState<AssetRecord[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<AssetRecord | null>(null); const [uploading, setUploading] = useState(false); const [dragging, setDragging] = useState(false); const input = useRef<HTMLInputElement>(null);
  const load = async () => { const r = await fetch("/api/assets", { cache: "no-store" }); const d = await r.json(); setAssets(d.assets ?? []); };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => assets.filter(a => a.filename.toLowerCase().includes(query.toLowerCase())), [assets, query]);
  async function upload(files: FileList | File[]) { const list = Array.from(files); if (!list.length) return; setUploading(true); for (const file of list) { const form = new FormData(); form.append("file", file); const r = await fetch("/api/assets", { method: "POST", body: form }); if (!r.ok) { const d = await r.json().catch(() => ({})); alert(d.error ?? `Could not upload ${file.name}`); } } await load(); setUploading(false); }
  return <main className="min-h-screen bg-zinc-50 p-8"><div className="mx-auto max-w-7xl">
    <div className="flex items-end justify-between"><div><div className="text-sm font-semibold text-zinc-500">WORKSPACE</div><h1 className="mt-1 text-3xl font-bold tracking-tight">Assets</h1><p className="mt-1 text-sm text-zinc-500">Your reusable image library.</p></div><button onClick={() => input.current?.click()} className="rounded-lg bg-zinc-900 px-4 py-2.5 text-sm font-semibold text-white">+ Upload Assets</button><input ref={input} hidden type="file" multiple accept="image/jpeg,image/png,image/gif,image/webp,image/svg+xml" onChange={e => e.target.files && upload(e.target.files)} /></div>
    <div onDragOver={e => {e.preventDefault(); setDragging(true)}} onDragLeave={() => setDragging(false)} onDrop={e => {e.preventDefault(); setDragging(false); upload(e.dataTransfer.files)}} className={`mt-6 rounded-2xl border-2 border-dashed p-8 text-center transition ${dragging ? "border-zinc-900 bg-white" : "border-zinc-200 bg-white"}`}><div className="text-sm font-medium">Drop images here</div><div className="mt-1 text-xs text-zinc-500">JPG, PNG, GIF, WebP, or SVG · up to 15 MB each</div>{uploading && <div className="mt-3 text-xs font-medium">Uploading…</div>}</div>
    <div className="mt-6 flex items-center gap-3"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search assets…" className="w-full max-w-md rounded-lg border bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-zinc-900"/><div className="text-sm text-zinc-500">{filtered.length} assets</div></div>
    <div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{filtered.map(asset => <button key={asset.id} onClick={() => setSelected(asset)} className="overflow-hidden rounded-xl border bg-white text-left hover:shadow-sm"><div className="aspect-square bg-zinc-100"><img src={asset.publicUrl} alt={asset.altText || asset.filename} className="h-full w-full object-contain" /></div><div className="p-3"><div className="truncate text-sm font-medium">{asset.filename}</div><div className="mt-1 text-xs text-zinc-500">{asset.width && asset.height ? `${asset.width} × ${asset.height}` : asset.mimeType} · {formatBytes(asset.fileSize)}</div></div></button>)}</div>
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-black/20" onClick={() => setSelected(null)}><aside onClick={e => e.stopPropagation()} className="h-full w-full max-w-md overflow-auto bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Asset Details</h2><button onClick={() => setSelected(null)} className="text-zinc-500">✕</button></div><div className="mt-5 overflow-hidden rounded-xl bg-zinc-100"><img src={selected.publicUrl} alt={selected.altText || selected.filename} className="max-h-80 w-full object-contain" /></div><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-xs uppercase tracking-wide text-zinc-400">Filename</dt><dd className="mt-1 font-medium">{selected.filename}</dd></div><div><dt className="text-xs uppercase tracking-wide text-zinc-400">Dimensions</dt><dd className="mt-1">{selected.width && selected.height ? `${selected.width} × ${selected.height}` : "Unknown"}</dd></div><div><dt className="text-xs uppercase tracking-wide text-zinc-400">Size</dt><dd className="mt-1">{formatBytes(selected.fileSize)}</dd></div><div><dt className="text-xs uppercase tracking-wide text-zinc-400">URL</dt><dd className="mt-1 break-all rounded bg-zinc-50 p-2 text-xs">{selected.publicUrl}</dd></div></dl></aside></div>}
  </div></main>;
}
