"use client";
import { useEffect, useRef, useState } from "react";
import type { AssetRecord } from "@/lib/assets/types";
export function AssetPicker({ value, onChange }: { value?: string | null; onChange: (asset: AssetRecord) => void }) {
  const [open, setOpen] = useState(false); const [assets, setAssets] = useState<AssetRecord[]>([]); const [q, setQ] = useState(""); const input = useRef<HTMLInputElement>(null);
  const load = async () => { const r = await fetch("/api/assets", { cache: "no-store" }); const d = await r.json(); setAssets(d.assets ?? []); };
  useEffect(() => { if (open) load(); }, [open]);
  async function upload(file?: File) { if (!file) return; const f = new FormData(); f.append("file", file); const r = await fetch("/api/assets", { method: "POST", body: f }); if (r.ok) { const d = await r.json(); onChange(d.asset); setOpen(false); } }
  const selected = assets.find(a => a.id === value);
  return <><button type="button" onClick={() => setOpen(true)} className="mt-2 flex w-full items-center gap-3 rounded-lg border p-2 text-left hover:bg-zinc-50">{selected ? <><img src={selected.publicUrl} className="h-10 w-10 rounded object-cover" alt=""/><span className="truncate text-sm">{selected.filename}</span></> : <span className="text-sm text-zinc-500">Choose an asset…</span>}</button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-6" onClick={() => setOpen(false)}><div onClick={e => e.stopPropagation()} className="w-full max-w-3xl rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Select Asset</h2><button onClick={() => setOpen(false)}>✕</button></div><div className="mt-4 flex gap-2"><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search assets…" className="flex-1 rounded-lg border px-3 py-2 text-sm"/><button onClick={() => input.current?.click()} className="rounded-lg bg-zinc-900 px-3 py-2 text-sm font-semibold text-white">Upload</button><input ref={input} hidden type="file" accept="image/*" onChange={e => upload(e.target.files?.[0])}/></div><div className="mt-5 grid max-h-[55vh] grid-cols-3 gap-3 overflow-auto sm:grid-cols-4"><button onClick={() => setOpen(false)} className="aspect-square rounded-lg border-2 border-dashed text-xs text-zinc-500">No image</button>{assets.filter(a => a.filename.toLowerCase().includes(q.toLowerCase())).map(a => <button key={a.id} onClick={() => { onChange(a); setOpen(false); }} className="overflow-hidden rounded-lg border text-left hover:ring-2 hover:ring-zinc-900"><img src={a.publicUrl} className="aspect-square w-full object-contain bg-zinc-100" alt={a.altText || a.filename}/><div className="truncate p-2 text-xs">{a.filename}</div></button>)}</div></div></div>}</>;
}
