"use client";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import type { StoredLink } from "@/lib/repository/link-store";
export function LinkPicker({ value, onChange }: { value?: string | null; onChange: (link: StoredLink) => void }) {
  const [open,setOpen]=useState(false),[links,setLinks]=useState<StoredLink[]>([]),[q,setQ]=useState("");
  useEffect(()=>{if(open)fetch("/api/links",{cache:"no-store"}).then(r=>r.json()).then(d=>setLinks(d.links??[]));},[open]);
  const selected=links.find(l=>l.id===value);
  return <><button type="button" onClick={()=>setOpen(true)} className="mt-2 w-full rounded-lg border p-2 text-left text-sm hover:bg-zinc-50">{selected?<><span className="font-medium">{selected.name}</span><span className="ml-2 text-zinc-400">{selected.destinationUrl}</span></>:<span className="text-zinc-500">Choose a managed link…</span>}</button>{open&&createPortal(<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-6" onClick={()=>setOpen(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Select Link</h2><button onClick={()=>setOpen(false)}>✕</button></div><div className="mt-4 flex gap-2"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search links…" className="flex-1 rounded-lg border px-3 py-2 text-sm"/><a href="/links" className="rounded-lg bg-zinc-900 px-3 py-2 text-sm font-semibold text-white">Manage Links</a></div><div className="mt-4 max-h-[50vh] overflow-auto divide-y">{links.filter(l=>(l.name+" "+l.destinationUrl).toLowerCase().includes(q.toLowerCase())).map(l=><button key={l.id} onClick={()=>{onChange(l);setOpen(false)}} className="block w-full p-4 text-left hover:bg-zinc-50"><div className="font-medium">{l.name}</div><div className="mt-1 truncate text-xs text-zinc-500">{l.destinationUrl}</div></button>)}{links.length===0&&<div className="p-8 text-center text-sm text-zinc-500">No managed links yet.</div>}</div></div></div>, document.body)}</>;
}
