"use client";
import { useEffect, useState } from "react";
import type { StoredLink } from "@/lib/repository/link-store";

export default function PageComponent() {
  const [links, setLinks] = useState<StoredLink[]>([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<StoredLink | null>(null);
  const load = async () => { try { const r = await fetch("/api/links", { cache: "no-store" }); const d = r.ok ? await r.json() : {}; setLinks(d.links ?? []); } catch { setLinks([]); } };
  useEffect(() => { load(); }, []);
  async function save(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const body = Object.fromEntries(form.entries()); const r = await fetch(editing ? `/api/links/${editing.id}` : "/api/links", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, trackingEnabled: true }) }); if (r.ok) { setOpen(false); setEditing(null); load(); } }
  async function remove(id: string) { if (!confirm("Delete this link?")) return; await fetch(`/api/links/${id}`, { method: "DELETE" }); load(); }
  return <div className="min-h-screen bg-zinc-50 p-8"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><div className="text-sm font-semibold text-zinc-500">VAULTFOUNDRY</div><h1 className="mt-1 text-3xl font-bold tracking-tight">Links</h1><p className="mt-1 text-sm text-zinc-500">Manage reusable destinations and tracking settings.</p></div><button onClick={() => { setEditing(null); setOpen(true); }} className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white">+ New Link</button></div>
  <div className="mt-8 overflow-hidden rounded-xl border bg-white">{links.length === 0 ? <div className="p-12 text-center text-sm text-zinc-500">No links yet. Create one to reuse it in buttons and images.</div> : <div className="divide-y">{links.map(l => <div key={l.id} className="flex items-center justify-between p-5"><div className="min-w-0"><div className="font-medium">{l.name}</div><div className="mt-1 truncate text-sm text-zinc-500">{l.destinationUrl}</div><div className="mt-2 text-xs text-zinc-400">{l.trackingEnabled ? "Tracking enabled" : "Tracking disabled"}</div></div><div className="ml-6 flex gap-2"><button onClick={() => { setEditing(l); setOpen(true); }} className="rounded-md border px-3 py-2 text-sm">Edit</button><button onClick={() => remove(l.id)} className="rounded-md border px-3 py-2 text-sm text-red-600">Delete</button></div></div>)}</div>}</div></div>
  {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-6"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{editing ? "Edit Link" : "New Link"}</h2><button type="button" onClick={() => setOpen(false)}>✕</button></div><div className="mt-5 space-y-4"><label className="block text-sm font-medium">Name<input name="name" defaultValue={editing?.name ?? ""} className="mt-1 w-full rounded-lg border p-2.5" required /></label><label className="block text-sm font-medium">Destination URL<input name="destinationUrl" type="url" defaultValue={editing?.destinationUrl ?? "https://"} className="mt-1 w-full rounded-lg border p-2.5" required /></label><label className="block text-sm font-medium">Description<textarea name="description" defaultValue={editing?.description ?? ""} className="mt-1 w-full rounded-lg border p-2.5" /></label><div className="rounded-lg bg-zinc-50 p-4"><div className="text-sm font-medium">UTM parameters</div><div className="mt-3 grid grid-cols-2 gap-3">{[["utmSource","Source"],["utmMedium","Medium"],["utmCampaign","Campaign"],["utmContent","Content"]].map(([name,label]) => <label key={name} className="text-xs font-medium">{label}<input name={name} defaultValue={(editing as any)?.[name] ?? ""} className="mt-1 w-full rounded border p-2 text-sm" /></label>)}</div></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white">Save Link</button></div></form></div>}
  </div>;
}
