"use client";
import { useEffect, useMemo, useState } from "react";
import { Blocks, Search, Trash2, Pencil, History, X, Tag } from "lucide-react";
import { Page } from "@/components/ui/page";
import type { EmailComponent } from "@/lib/email";

interface BlockVersion { version:number; component:EmailComponent; createdAt:string; }
interface Block { id:string; name:string; description?:string; category?:string; component:EmailComponent; version:number; createdAt:string; updatedAt:string; versions?:BlockVersion[]; }

export default function BlocksPage(){
  const [items,setItems]=useState<Block[]>([]); const [q,setQ]=useState(""); const [category,setCategory]=useState("All");
  const [editing,setEditing]=useState<Block|null>(null); const [historyBlock,setHistoryBlock]=useState<Block|null>(null);
  const load=()=>fetch("/api/blocks").then(r=>r.ok?r.json():[]).then(setItems).catch(()=>setItems([]));
  useEffect(()=>{load()},[]);
  const categories=useMemo(()=>["All",...Array.from(new Set(items.map(b=>b.category||"General"))).sort()],[items]);
  const filtered=items.filter(b=>(category==="All"||(b.category||"General")===category)&&`${b.name} ${b.description??""} ${b.category??""}`.toLowerCase().includes(q.toLowerCase()));
  const remove=async(id:string)=>{if(!confirm("Delete this block?"))return;await fetch(`/api/blocks/${id}`,{method:"DELETE"});setItems(x=>x.filter(i=>i.id!==id))};
  const save=async(data:{name:string;description:string;category:string})=>{if(!editing)return;const r=await fetch(`/api/blocks/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(data)});if(r.ok){const updated=await r.json();setItems(x=>x.map(i=>i.id===updated.id?updated:i));setEditing(null)}};
  return <Page title="Blocks" description="Reusable sections and content components for your emails.">
    <div className="mb-5 flex flex-wrap items-center gap-3"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-2.5 text-zinc-400" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search blocks…" className="w-full rounded-lg border bg-white py-2 pl-9 pr-3 text-sm"/></div><div className="flex flex-wrap gap-1 rounded-lg border bg-white p-1">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-md px-3 py-1.5 text-xs font-medium ${category===c?"bg-zinc-900 text-white":"text-zinc-500 hover:bg-zinc-50"}`}>{c}</button>)}</div></div>
    {filtered.length===0?<div className="rounded-xl border border-dashed bg-white p-12 text-center"><Blocks className="mx-auto mb-3 text-zinc-300"/><div className="font-medium">No reusable blocks yet</div><p className="mt-1 text-sm text-zinc-500">Select a component in the builder and choose “Save as block.”</p></div>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{filtered.map(b=><div key={b.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="mb-4 flex h-32 items-center justify-center rounded-lg bg-zinc-50 p-3">{blockPreview(b.component)}</div><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{b.name}</h2><p className="mt-1 line-clamp-2 text-xs text-zinc-500">{b.description||b.component.type}</p></div><div className="flex gap-1"><button title="Edit" onClick={()=>setEditing(b)} className="rounded p-1.5 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-900"><Pencil size={15}/></button><button title="Version history" onClick={()=>setHistoryBlock(b)} className="rounded p-1.5 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-900"><History size={15}/></button><button title="Delete" onClick={()=>remove(b.id)} className="rounded p-1.5 text-zinc-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></div></div><div className="mt-3 flex items-center gap-2 text-[10px] uppercase tracking-widest text-zinc-400"><Tag size={11}/>{b.category||"General"}<span>·</span>v{b.version}</div></div>)}</div>}
    {editing&&<EditBlock block={editing} onClose={()=>setEditing(null)} onSave={save}/>} {historyBlock&&<HistoryModal block={historyBlock} onClose={()=>setHistoryBlock(null)}/>} 
  </Page>
}

function EditBlock({block,onClose,onSave}:{block:Block;onClose:()=>void;onSave:(x:{name:string;description:string;category:string})=>void}){const [name,setName]=useState(block.name);const [description,setDescription]=useState(block.description||"");const [category,setCategory]=useState(block.category||"General");return <Modal title="Edit block" onClose={onClose}><label className="mb-4 block text-xs font-semibold">Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-lg border p-2 text-sm"/></label><label className="mb-4 block text-xs font-semibold">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-1.5 w-full rounded-lg border p-2 text-sm"/></label><label className="mb-6 block text-xs font-semibold">Category<input value={category} onChange={e=>setCategory(e.target.value)} className="mt-1.5 w-full rounded-lg border p-2 text-sm"/></label><div className="flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button onClick={()=>onSave({name,description,category})} disabled={!name.trim()} className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Save changes</button></div></Modal>}
function HistoryModal({block,onClose}:{block:Block;onClose:()=>void}){const versions=[...(block.versions||[])].sort((a,b)=>b.version-a.version);return <Modal title={`${block.name} history`} onClose={onClose}><div className="space-y-2">{versions.length?versions.map(v=><div key={v.version} className="flex items-center justify-between rounded-lg border p-3"><div><div className="font-medium">Version {v.version}</div><div className="text-xs text-zinc-500">{new Date(v.createdAt).toLocaleString()}</div></div>{v.version===block.version&&<span className="rounded-full bg-zinc-100 px-2 py-1 text-[10px] font-semibold uppercase">Current</span>}</div>):<div className="text-sm text-zinc-500">No historical versions yet.</div>}</div></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-6"><div className="w-full max-w-md rounded-2xl border bg-white p-5 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div className="text-lg font-semibold">{title}</div><button onClick={onClose} className="rounded p-1 hover:bg-zinc-100"><X size={17}/></button></div>{children}</div></div>}
function blockPreview(n:EmailComponent):React.ReactNode{const p=n.props??{};if(n.type==="heading")return <div className="text-xl font-bold">{String(p.content??"Heading")}</div>;if(n.type==="text")return <div className="text-sm text-zinc-500">{String(p.content??"Text")}</div>;if(n.type==="button")return <div className="rounded bg-zinc-900 px-3 py-2 text-xs font-semibold text-white">{String(p.text??"Button")}</div>;if(n.type==="image")return <div className="flex h-20 w-full items-center justify-center bg-zinc-200 text-xs text-zinc-500">Image</div>;return <div className="text-xs text-zinc-500">{n.type}</div>}
